# @package network
defaults:
  - _self_

network_type: "chitransformer"
encoder_type: "identity"
emb_dim: 256
num_layers: 8
dropout: 0.0
encoder_dropout: 0.0
timestep_emb_dim: 128

# ChiTransformer specific configs
nhead: 4
attn_dropout: 0.3
n_cond_layers: 0  # Number of conditioning encoder layers
timestep_emb_type: "positional"  # Options: positional, sinusoidal, fourier