# @package network
defaults:
  - _base
  - _self_

network_type: "chitransformer"
emb_dim: 384
num_layers: 8
dropout: 0.0
timestep_emb_dim: 128

# ChiTransformer specific configs
n_heads: 6
attn_dropout: 0.1
n_cond_layers: 0  # Number of conditioning encoder layers
timestep_emb_type: "positional"  # Options: positional, sinusoidal, fourier
