# @package network
defaults:
  - _self_

network_type: "mlp"
encoder_type: "identity"
emb_dim: 512
num_layers: 6
dropout: 0.1
encoder_dropout: 0.0
expansion_factor: 4
timestep_emb_dim: 128
# Image encoder configs (used when encoder_type is "image")
rgb_model_name: "resnet18"
use_seq: true
keep_horizon_dims: true
